### ISSUE TITLE
V30: Three graphics missing

### ISSUE THREAD

**Issue by aquileia** [aquileia/FP-WS2014#4]
The following graphics still need to be committed:
* tau_osci.pdf
* setup_Nd:YAG.pdf
* setup_Nd:YAG_SHG.pdf

**Comment by neji1985** [comment]
Issue solved:
uploaded 
tau_osci.pdf
setup_Nd:YAG.pdf
setup_Nd:YAG_SHG.pdf
to V30_Nonlinear_Optics/graphics/
